apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: nosql
type: Opaque
stringData:
  mongo-root-username: admin
  mongo-root-password: admin123
  spring-mongo-uri: mongodb://admin:admin123@mongodb-service:27017/imagedb?authSource=admin
