spring.application.name=gateway
server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=message-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://message-service:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/message/**

spring.cloud.gateway.server.webflux.routes[1].id=image-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://image-service:8080
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/image/**
