apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: message-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: message-service
  namespaceSelector:
    matchNames:
      - nosql
  endpoints:
    - port: "8080"
      path: /metrics
      interval: 15s