apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
  namespace: nosql
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: angular-app