apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: nosql
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: gateway-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 90
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          envFrom:
            - secretRef:
                name: gateway-secret